### PR TITLE
apply arithmetic operations in basic_similarterm only if binary

### LINKED ISSUE #500: Regression: infinite loop during simplification on v1
The following code hits an infinite loop:
```julia
using SymbolicUtils
@syms x1::LiteralReal x2::LiteralReal
s = cos(x1*3.2) - (x2*5.8) + x2*1.2
simplify(s)
```
On v1, this code hangs on the `simplify(s)` and hasn't completed in 30 minutes. This works on v0.19.

Defining `@syms x1 x2` works (auto-simplifies).

When I interrupt the simplification, this is the stacktrace (it changes every time I interrupt it):

```julia
Failed to apply rule cot(~x) ^ 2 + 1 => csc(~x) ^ 2 on expression 1.2x2 + cos(3.2x1) - 5.8x2
Stacktrace:
  [1] (::SymbolicUtils.Rule{SymbolicUtils.BasicSymbolic{Any}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#192#273"})(term::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/rule.jl:145
  [2] (::SymbolicUtils.ACRule{typeof(Combinatorics.permutations), SymbolicUtils.Rule{SymbolicUtils.BasicSymbolic{Any}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#192#273"}})(term::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/rule.jl:407
  [3] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
  [4] (::SymbolicUtils.Rewriters.Chain)(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:69
  [5] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
  [6] (::SymbolicUtils.Rewriters.Chain)(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:69
  [7] (::SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58
  [8] (::SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:200
  [9] (::SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58
 [10] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
 [11] (::SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:122
 [12] IfElse
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58 [inlined]
 [13] (::SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.IfElse{typeof(istree), SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}}}, SymbolicUtils.Rewriters.Empty}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:188
 [14] simplify(x::SymbolicUtils.BasicSymbolic{LiteralReal}; expand::Bool, polynorm::Nothing, threaded::Bool, simplify_fractions::Bool, thread_subtree_cutoff::Int64, rewriter::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/simplify.jl:41
 [15] simplify(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/simplify.jl:16
 [16] top-level scope
    @ REPL[5]:1

caused by: InterruptException:
Stacktrace:
  [1] getindex
    @ ./tuple.jl:29 [inlined]
  [2] car
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:179 [inlined]
  [3] (::SymbolicUtils.var"#loop#99"{SymbolicUtils.var"#success#85"{SymbolicUtils.var"#192#273"}})(term::SymbolicUtils.LL{SubArray{Any, 1, Vector{Any}, Tuple{Vector{Int64}}, false}}, bindings′::Base.ImmutableDict{Symbol, Any}, matchers′::SymbolicUtils.LL{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/matchers.jl:101
  [4] (::SymbolicUtils.var"#97#100"{SymbolicUtils.BasicSymbolic{LiteralReal}, Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}})(b::Base.ImmutableDict{Symbol, Any}, n::Int64)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/matchers.jl:102
  [5] (::SymbolicUtils.var"#literal_matcher#94"{typeof(+)})(next::SymbolicUtils.var"#97#100"{SymbolicUtils.BasicSymbolic{LiteralReal}, Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, data::SymbolicUtils.BasicSymbolic{LiteralReal}, bindings::Base.ImmutableDict{Symbol, Any})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/matchers.jl:11
  [6] (::SymbolicUtils.var"#loop#99"{SymbolicUtils.var"#success#85"{SymbolicUtils.var"#192#273"}})(term::SymbolicUtils.BasicSymbolic{LiteralReal}, bindings′::Base.ImmutableDict{Symbol, Any}, matchers′::Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/matchers.jl:101
  [7] (::SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}})(success::SymbolicUtils.var"#success#85"{SymbolicUtils.var"#192#273"}, data::Tuple{SymbolicUtils.BasicSymbolic{LiteralReal}}, bindings::Base.ImmutableDict{Symbol, Any})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/matchers.jl:106
  [8] (::SymbolicUtils.Rule{SymbolicUtils.BasicSymbolic{Any}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#192#273"})(term::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/rule.jl:143
  [9] (::SymbolicUtils.ACRule{typeof(Combinatorics.permutations), SymbolicUtils.Rule{SymbolicUtils.BasicSymbolic{Any}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(+)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(^)}, SymbolicUtils.var"#term_matcher#98"{Tuple{SymbolicUtils.var"#literal_matcher#94"{typeof(cot)}, SymbolicUtils.var"#slot_matcher#95"{SymbolicUtils.Slot{typeof(SymbolicUtils.alwaystrue)}}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#literal_matcher#94"{Int64}}}, SymbolicUtils.var"#192#273"}})(term::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/rule.jl:407
 [10] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
 [11] (::SymbolicUtils.Rewriters.Chain)(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:69
 [12] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
 [13] (::SymbolicUtils.Rewriters.Chain)(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:69
 [14] (::SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58
 [15] (::SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:200
 [16] (::SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58
 [17] macro expansion
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/utils.jl:11 [inlined]
 [18] (::SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:122
 [19] IfElse
    @ ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:58 [inlined]
 [20] (::SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.IfElse{typeof(istree), SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig_exp), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#218#302", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#219#303", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(similarterm), false}}}, SymbolicUtils.Rewriters.Empty}})(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/pO4d6/src/rewriters.jl:188
 [21] simplify(x::SymbolicUtils.BasicSymbolic{LiteralReal}; expand::Bool, polynorm::Nothing, threaded::Bool, simplify_fractions::Bool, thread_subtree_cutoff::Int64, rewriter::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/simplify.jl:41
 [22] simplify(x::SymbolicUtils.BasicSymbolic{LiteralReal})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/pO4d6/src/simplify.jl:16
```

### PR DESCRIPTION
**Pull request by shashi**
fixes #500

### CODE REVIEW

File: test/rulesets.jl [hunk 1]
```diff
@@ -54,6 +54,18 @@ end
...
+@testset "LiteralReal" begin
+    @syms x1::LiteralReal x2::LiteralReal
+    s = cos(x1 * 3.2) - x2 * 5.8 + x2 * 1.2
+    @eqtest s == cos(x1 * 3.2) - x2 * 5.8 + x2 * 1.2
+
+    # Prevents automatic simplification:
+    @eqtest s != cos(x1 * 3.2) - x2 * 4.6
+
+    # However, manual simplification should still work:
+    @eqtest simplify(s) == cos(3.2(x1^1)) - 4.6x2
```
Comment (shashi) [inline test/rulesets.jl:66]: shouldn't this become

```
cos(3.2x1) - 4.6x2
```
?

My update does this....

Comment (shashi) [reply test/rulesets.jl:66]: Ok I see it was leaving the `^1` before because of a missed case. I can safely change the test here I think.

Comment (shashi) [reply test/rulesets.jl:66]: Although, it also changes it further. `LiteralReal` represents `cos(3.2(x1^1)) - 4.6x2` as `cos(3.2(x1^1)) - (4.6*x2)`. simplification turns it into `cos(3.2(x1^1)) + -4.6 * x2`
