### PR TITLE
Fix division and printing

### LINKED ISSUE #163: Bug in division rules
This is in SymbolicUtils v0.7.2:
```julia
julia> using SymbolicUtils

julia> @syms μ σ x
(μ, σ, x)

julia> simplify(-log(σ) - (x - μ)^2 / (2*σ^2))
-1log(σ) + -2(σ^-2)*((x + -1μ)^2)
```

That `-2` should be `-0.5`. Looks like a bug in the rules?

### PR DESCRIPTION
**Pull request by YingboMa**
Fix #163

### CODE REVIEW

File: src/types.jl [hunk 1]
```diff
@@ -648,8 +645,9 @@ Base.show(io::IO, p::Pow) = show_term(io, p)
 ^(a::Number, b::SN) = Pow(a, b)
 
 function ^(a::Mul, b::Number)
+    coeff = a.coeff isa Integer && b isa Integer ? (a.coeff//1) ^ b : a.coeff ^ b
```
Comment (shashi) [inline src/types.jl:648]: Cool trick!

**Review by shashi — APPROVED** [review]
Lgtm!
