### PR TITLE
Fix substitute when using metadata

### LINKED ISSUE #283: Metadata of Term changes in substitution
```julia
using SymbolicUtils
using SymbolicUtils: Term
@syms a b f t
f = Term(f, (t,)) # create term f(t)
f = setmetadata(f, Bool, true)
hasmetadata(f, Bool) # true
newf = substitute(f, Dict(a=>b)) # unrelated substitution
hasmetadata(newf, Bool) # false
```
I think this is a M(not)WE for `SymbolicUtils`. The problem came up after recent changes to MTK SciML/ModelingToolkit.jl/pull/943
```julia
using ModelingToolkit
using ModelingToolkit: isparameter
@parameters t a(t)
@variables x(t) y(t)
isparameter(a) # true
isparameter(substitute(a, x=>y)) # false :(
```

### PR DESCRIPTION
**Pull request by shashi**
fixes #283

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]

File: src/types.jl [hunk 1]
```diff
@@ -56,8 +56,16 @@ symtype(x) = typeof(x)
 
 symtype(::Symbolic{T}) where {T} = T
 
+"""
+    metadata(s)
+Get all the metadata of a term or `nothing` if no metadata is defined.
+
+"""
+metadata(s::Symbolic) = s.metadata
+metadata(s::Any) = x
```
Comment (adamslc) [inline src/types.jl:65]:
```suggestion
metadata(s::Any) = nothing
```

**Review by adamslc — CHANGES_REQUESTED** [review]
One typo to fix.

**Comment by shashi** [comment]
@adamslc thanks!
